"""Stable failure taxonomy shared across signals, reports, health, and registry."""

from __future__ import annotations

from enum import IntEnum, StrEnum
from typing import TypeAlias


class FailureCode(StrEnum):
    CONFIG_FAILURE = "CONFIG_FAILURE"
    DATA_FAILURE = "DATA_FAILURE"
    DATA_CONTRACT_FAILED = "DATA_CONTRACT_FAILED"
    DATA_DISAGREEMENT = "DATA_DISAGREEMENT"
    BACKTEST_FAILURE = "BACKTEST_FAILURE"
    NOTIFICATION_FAILURE = "NOTIFICATION_FAILURE"
    INTERNAL_FAILURE = "INTERNAL_FAILURE"
    RUN_FAILED = "RUN_FAILED"
    NO_RUN_HISTORY = "NO_RUN_HISTORY"
    HEALTH_SCORE_LOW = "HEALTH_SCORE_LOW"
    SAFETY_VERDICT_BLOCKED = "SAFETY_VERDICT_BLOCKED"
    OPERATIONAL_RUN_STALE = "OPERATIONAL_RUN_STALE"
    OPERATIONAL_RUN_ACTIVE = "OPERATIONAL_RUN_ACTIVE"
    SIGNAL_PUBLICATION_MISSING = "SIGNAL_PUBLICATION_MISSING"
    SIGNAL_PUBLICATION_INVALID = "SIGNAL_PUBLICATION_INVALID"
    COST_FRAGILE = "COST_FRAGILE"
    COST_NOT_EVALUATED = "COST_NOT_EVALUATED"
    LIVE_PRICE_SAFETY_FAILED = "LIVE_PRICE_SAFETY_FAILED"
    SURVIVORSHIP_GATE_FAILED = "SURVIVORSHIP_GATE_FAILED"
    SHADOW_PROMOTION_FAILED = "SHADOW_PROMOTION_FAILED"

    NOT_A_BUY_SIGNAL = "NOT_A_BUY_SIGNAL"
    PORTFOLIO_FILE_UNAVAILABLE = "PORTFOLIO_FILE_UNAVAILABLE"
    UNVERIFIED_PRICE_DATA = "UNVERIFIED_PRICE_DATA"
    REFERENCE_DATA_CONFLICT = "REFERENCE_DATA_CONFLICT"
    OPENFIGI_UNMAPPED = "OPENFIGI_UNMAPPED"
    EVENT_DATA_NOTE = "EVENT_DATA_NOTE"
    UNMAPPED_TICKER = "UNMAPPED_TICKER"

    MAX_POSITION_COUNT_EXCEEDED = "MAX_POSITION_COUNT_EXCEEDED"
    SINGLE_POSITION_EXCEEDED = "SINGLE_POSITION_EXCEEDED"
    LIQUIDITY_INSUFFICIENT = "LIQUIDITY_INSUFFICIENT"
    UNDERLYING_EXPOSURE_EXCEEDED = "UNDERLYING_EXPOSURE_EXCEEDED"
    SECTOR_EXPOSURE_EXCEEDED = "SECTOR_EXPOSURE_EXCEEDED"
    LEVERAGED_ETF_VALUE_EXCEEDED = "LEVERAGED_ETF_VALUE_EXCEEDED"
    ADJUSTED_GROSS_EXPOSURE_EXCEEDED = "ADJUSTED_GROSS_EXPOSURE_EXCEEDED"
    FACTOR_EXPOSURE_EXCEEDED = "FACTOR_EXPOSURE_EXCEEDED"
    MIN_CASH_BREACHED = "MIN_CASH_BREACHED"
    MAX_INVESTED_EXCEEDED = "MAX_INVESTED_EXCEEDED"
    DAILY_LOSS_LIMIT_BREACHED = "DAILY_LOSS_LIMIT_BREACHED"
    WEEKLY_LOSS_LIMIT_BREACHED = "WEEKLY_LOSS_LIMIT_BREACHED"
    MONTHLY_DRAWDOWN_BREACHED = "MONTHLY_DRAWDOWN_BREACHED"


FailureCodeValue: TypeAlias = str


class ProcessExitCode(IntEnum):
    GENERAL_FAILURE = 1
    CONFIG_FAILURE = 10
    DATA_FAILURE = 20
    BACKTEST_FAILURE = 30
    SAFETY_GATE_FAILED = 40
    NOTIFICATION_FAILURE = 50
    INTERNAL_FAILURE = 70


_DATA_FAILURE_CODES = {
    FailureCode.DATA_FAILURE,
    FailureCode.DATA_CONTRACT_FAILED,
    FailureCode.DATA_DISAGREEMENT,
    FailureCode.LIVE_PRICE_SAFETY_FAILED,
    FailureCode.UNVERIFIED_PRICE_DATA,
    FailureCode.REFERENCE_DATA_CONFLICT,
    FailureCode.OPENFIGI_UNMAPPED,
    FailureCode.UNMAPPED_TICKER,
    FailureCode.SIGNAL_PUBLICATION_INVALID,
}

_SAFETY_FAILURE_CODES = {
    FailureCode.NO_RUN_HISTORY,
    FailureCode.HEALTH_SCORE_LOW,
    FailureCode.SAFETY_VERDICT_BLOCKED,
    FailureCode.OPERATIONAL_RUN_STALE,
    FailureCode.OPERATIONAL_RUN_ACTIVE,
    FailureCode.SIGNAL_PUBLICATION_MISSING,
    FailureCode.COST_FRAGILE,
    FailureCode.COST_NOT_EVALUATED,
    FailureCode.SURVIVORSHIP_GATE_FAILED,
    FailureCode.SHADOW_PROMOTION_FAILED,
    FailureCode.PORTFOLIO_FILE_UNAVAILABLE,
    FailureCode.MAX_POSITION_COUNT_EXCEEDED,
    FailureCode.SINGLE_POSITION_EXCEEDED,
    FailureCode.LIQUIDITY_INSUFFICIENT,
    FailureCode.UNDERLYING_EXPOSURE_EXCEEDED,
    FailureCode.SECTOR_EXPOSURE_EXCEEDED,
    FailureCode.LEVERAGED_ETF_VALUE_EXCEEDED,
    FailureCode.ADJUSTED_GROSS_EXPOSURE_EXCEEDED,
    FailureCode.FACTOR_EXPOSURE_EXCEEDED,
    FailureCode.MIN_CASH_BREACHED,
    FailureCode.MAX_INVESTED_EXCEEDED,
    FailureCode.DAILY_LOSS_LIMIT_BREACHED,
    FailureCode.WEEKLY_LOSS_LIMIT_BREACHED,
    FailureCode.MONTHLY_DRAWDOWN_BREACHED,
}


def normalize_failure_code(
    value: object, default: FailureCode = FailureCode.INTERNAL_FAILURE
) -> str:
    """Return a canonical failure code value for persisted artifacts."""
    if isinstance(value, FailureCode):
        return value.value
    if isinstance(value, str):
        normalized = value.strip().upper()
        try:
            return FailureCode(normalized).value
        except ValueError:
            return default.value
    return default.value


def process_exit_code(value: object) -> int:
    """Map a persisted failure code to a stable process exit code."""
    failure_code = FailureCode(normalize_failure_code(value))
    if failure_code == FailureCode.CONFIG_FAILURE:
        return ProcessExitCode.CONFIG_FAILURE
    if failure_code in _DATA_FAILURE_CODES:
        return ProcessExitCode.DATA_FAILURE
    if failure_code == FailureCode.BACKTEST_FAILURE:
        return ProcessExitCode.BACKTEST_FAILURE
    if failure_code == FailureCode.NOTIFICATION_FAILURE:
        return ProcessExitCode.NOTIFICATION_FAILURE
    if failure_code in _SAFETY_FAILURE_CODES:
        return ProcessExitCode.SAFETY_GATE_FAILED
    return ProcessExitCode.INTERNAL_FAILURE
